apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::636619205051:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1038FTKLJC4ZE
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::636619205051:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-01T16:23:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "975"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: be2b98df-3617-4c9a-95ad-9ef11aeab3b8
